New ToS
OpenZeppelin/openzeppelin.com pull request #158
Opened 2021-03-10 20:36 UTC by jalex206

2021-03-10 23:33 UTC, abcoathup requested changes
We should remove duplicate headings, fix numberings and bullet point formatting.
Nice to haves are bolding defined terms.

2021-03-10 23:33 UTC, abcoathup commented on tos.md
> +6.2 The Services were not designed or intended to process or manage any Protected Information. OpenZeppelin will not be responsible for damages associated with Protected Information created, stored,
```suggestion
6.2 The Services were not designed or intended to process or manage any Protected Information. OpenZeppelin will not be responsible for damages associated with Protected Information created, stored, shared or processed through the Services. &quot;**Protected Information**&quot; means information that is subject to specific regulations or laws that impose increased protections and/or obligations with respect to handling that type of information or that is not appropriate for use in the Services, as intended. Protected Information includes, without limitation, any credit or debit card and magnetic stripe information, social security numbers, driver&#39;s license numbers, passport numbers, government issued identification numbers, health-related information, biometric data, financial account information, or information deemed &quot;sensitive&quot; under applicable laws (such as racial or ethnic origin, political opinions, or religious or philosophical beliefs).
```
Bold defined terms

2021-03-10 23:33 UTC, abcoathup commented on tos.md
> +7.1 The Services may contain links to other websites (&quot;Linked Sites&quot;). The Linked Sites are not under the control of OpenZeppelin and OpenZeppelin is not responsible or liable for the conte
```suggestion
7.1 The Services may contain links to other websites (&quot;**Linked Sites**&quot;). The Linked Sites are not under the control of OpenZeppelin and OpenZeppelin is not responsible or liable for the contents of any Linked Site, including without limitation any link or content contained in a Linked Site, or any changes or updates to a Linked Site. When you click on a link to a Linked Site, we may not warn you that you have left our Services and are subject to the terms and conditions (including privacy policies) of another website or destination. OpenZeppelin is providing these links to you only as a convenience, and the inclusion of any link does not imply endorsement by OpenZeppelin of the site or any association with its operators. You use any Linked Sites at your own risk. When you leave the Services, our Terms and policies no longer govern. You should review applicable terms and policies, including privacy and data gathering practices, of the Linked Sites, and should make whatever investigation you feel necessary or appropriate before proceeding with any interaction or transaction with any third party.
```
Bold defined terms

2021-03-10 23:33 UTC, abcoathup commented on tos.md
> +8.5 OpenZeppelin may suspend your access to any Services, including Defender, immediately if: (a) you have undisputed amounts more than 5 days past due; (b) there is reason to believe that your use o
```suggestion
8.5 OpenZeppelin may suspend your access to any Services, including Defender, immediately if: (a) you have undisputed amounts more than 5 days past due; (b) there is reason to believe that your use of Services is fraudulent or that you or any of your users are using the Services in a way that creates a security vulnerability or may disrupt others&#39; use of the Services; (c) there is scheduled or emergency maintenance; or (d) OpenZeppelin determines, in its sole discretion, that providing the Services is prohibited by applicable law, or it has become impractical or unfeasible for any legal or regulatory reason to the provide the Services.
```
Renumber as there is no (c)

2021-03-10 23:33 UTC, abcoathup commented on tos.md
> +9.1 If you select a paid tier of Defender, OpenZeppelin will bill you in advance for use of the Services on a monthly basis. All paid subscription terms begin on the 1st day of the month and continue
```suggestion
9.1 If you select a paid tier of Defender, OpenZeppelin will bill you in advance for use of the Services on a monthly basis. All paid subscription terms begin on the 1st day of the month and continue to the last day of the month (each, a &quot;**Subscription Term**&quot;). Your subscription will automatically renew on a monthly basis until terminated pursuant to these Terms.
```
Bold defined terms.

2021-03-10 23:33 UTC, abcoathup commented on tos.md
> +
```suggestion

```
Formatting of bullet points in 13.1 need to be updated

2021-03-10 23:33 UTC, abcoathup commented on tos.md
> +
```suggestion
```
Remove blank line between bullet points

2021-03-10 23:33 UTC, abcoathup commented on tos.md
> +
```suggestion
```
Remove blank line between bullet points

2021-03-10 23:33 UTC, abcoathup commented on tos.md
> +
```suggestion
```
Remove blank line between bullet points

2021-03-10 23:33 UTC, abcoathup commented on tos.md
> +
```suggestion
```
Remove blank line between bullet points

2021-03-10 23:33 UTC, abcoathup commented on tos.md
> +
```suggestion
```
Remove blank line between bullet points

2021-03-10 23:33 UTC, abcoathup commented on tos.md
> +
```suggestion
```
Remove blank line between bullet points

2021-03-10 23:33 UTC, abcoathup commented on tos.md
> +13.1 If you believe that your copyright or the copyright of a person on whose behalf you are authorized to act has been infringed, please provide a written notice to legal@openzeppelin.com containing
```suggestion
13.1 If you believe that your copyright or the copyright of a person on whose behalf you are authorized to act has been infringed, please provide a written notice to [legal@openzeppelin.com](mailto:legal@openzeppelin.com) containing the following information:
```
Add link to email

2021-03-10 23:33 UTC, abcoathup commented on tos.md
> +15.1 Any dispute, claim, suit, action, cause of action, demand or proceeding arising out or in connection with these Terms (any of the foregoing occurrences, a &quot;Dispute&quot;), or the breach, te
```suggestion
15.1 Any dispute, claim, suit, action, cause of action, demand or proceeding arising out or in connection with these Terms (any of the foregoing occurrences, a &quot;**Dispute**&quot;), or the breach, termination or invalidity thereof shall first be endeavored to be settled through amicable negotiations in good faith by you and OpenZeppelin. If you and OpenZeppelin cannot agree how to resolve such Dispute within thirty (30) consecutive calendar days after the date a notice with respect to such Dispute is received by the other party, then either you or OpenZeppelin may, as appropriate, commence an arbitration proceeding. Such Dispute shall subsequently (and exclusively) be submitted to three arbitrators. The nomination of the arbitrators and the rules of arbitration shall be in accordance with the Rules of Arbitration of Cayman Islands. The seat of the arbitral tribunal shall be Cayman Islands. Language of the proceedings shall be English. The arbitral award is final and binding upon the parties. The arbitration fees will be borne by the losing party except otherwise awarded by the arbitral tribunal. The parties undertake to carry out the arbitral award in accordance with the modalities of said reward. Any Dispute that is not or cannot be subject to arbitration will be resolved by the courts of Cayman Islands governed by the laws of the Cayman Islands.
```
Bold defined terms

2021-03-10 23:33 UTC, abcoathup commented on tos.md
> +**1. Types of Users**
All headings could be changed from bold to Heading 2 as per previous version.

2021-03-11 00:14 UTC, abcoathup approved these changes
LGTM

2021-03-11 00:16 UTC, abcoathup approved these changes

2021-03-11 13:09 UTC, spalladino approved these changes

2021-03-11 13:09 UTC, merged